$schema: "http://json-schema.org/draft-04/schema#"

id: "project"
title: Project
type: object
namespace: null
category: administrative
program: '*'
project: '*'
description: >-
  Any specifically defined piece of work that is undertaken or attempted to meet a
  single requirement. (NCIt C47885)
additionalProperties: false
submittable: true

systemProperties:
  - id
  - state
  - released
  - releasable
  - intended_release_date

links:
  - name: programs
    backref: projects
    label: member_of
    target_type: program
    multiplicity: many_to_one
    required: true

required:
  - code
  - name
  - programs
  - dbgap_accession_number

uniqueKeys:
  - [id]
  - [code]

properties:

  type:
    type: string

  id:
    $ref: "_definitions.yaml#/uuid"
    description: >-
      UUID for the project.
    systemAlias: node_id

  name:
    description: >-
      Display name/brief description for the project.
    type: string

  code:
    description: >-
      Unique identifier for the project.
    type: string

  investigator_name:
    description: >-
      Name of the principal investigator for the project.
    type: string

  investigator_affiliation:
    description: >-
      The investigator's affiliation with respect to a research institution.
    type: string

  date_collected:
    description: >-
      The date or date range in which the project data was collected.
    type: string

  availability_type:
    description: >-
      Is the project open or restricted?
    enum:
      - Open
      - Restricted

  availability_mechanism:
    description: >-
      Mechanism by which the project will be made avilable.
    type: string

  support_source:
    description: >-
      The name of source providing support/grant resources.
    type: string

  support_id:
    description: >-
      The ID of the source providing support/grant resources.
    type: string

  state:
    description: >-
      The possible states a project can be in.  All but `open` are equivalent to some
      type of locked state.
    default: open
    enum:
      - open
      - review
      - submitted
      - processing
      - closed
      - legacy

  released:
    description: >-
      To release a project is to tell the GDC to include all submitted entities in
      the next GDC index.
    type: boolean
    default: false

  releasable:
    description: >-
      A project can only be released by the user when `releasable` is true.
    type: boolean
    default: false

  intended_release_date:
    description: >-
      Tracks a Project's intended release date.
    type: string
    format: date-time

  dbgap_accession_number:
    description: >-
      The dbgap accession number provided for the project.
    type: string

  programs:
    $ref: "_definitions.yaml#/to_one"
